spring.application.name=U5W3D5
spring.config.import=file:env.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/U5W3D5
spring.datasource.username=postgres
spring.datasource.password=${postgresql.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud_name=${cloud_name}
cloudinary.api_key=${api_key}
cloudinary.api_secret=${api_secret}

#jwt
#durata in millisecondi, corrisponde a 15 minuti
jwt.duration=900000
jwt.secret=abcdabcdabcdabcdabcdabcdabcdabcd